name: multi_thumb_slider
description: A slider with multiple thumbs.
 The behavior of the slider is similar to the official Slider widget. 
 The MultiThumbSlider should have at least 3 thumbs. For less thumbs, 
 use Slider or the RangeSlider.
homepage: https://github.com/codeOfJannik/multi_thumb_slider
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null

